 version: '2'
 services:
   nginx:
     build: nginx/.
     ports:
       - "8080:80"
   app:
     build: service/.
     ports:
       - "5000:5000"
   auth:
     build: auth/.
     ports:
       - "8000:8000"
